// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MrGeorge2/hejdusekj/ent/language"
	"github.com/MrGeorge2/hejdusekj/ent/localization"
	"github.com/MrGeorge2/hejdusekj/ent/predicate"
)

// LocalizationUpdate is the builder for updating Localization entities.
type LocalizationUpdate struct {
	config
	hooks    []Hook
	mutation *LocalizationMutation
}

// Where appends a list predicates to the LocalizationUpdate builder.
func (lu *LocalizationUpdate) Where(ps ...predicate.Localization) *LocalizationUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetLanguageID sets the "language_id" field.
func (lu *LocalizationUpdate) SetLanguageID(i int) *LocalizationUpdate {
	lu.mutation.SetLanguageID(i)
	return lu
}

// SetLocalizationValue sets the "localizationValue" field.
func (lu *LocalizationUpdate) SetLocalizationValue(s string) *LocalizationUpdate {
	lu.mutation.SetLocalizationValue(s)
	return lu
}

// SetLanguage sets the "language" edge to the Language entity.
func (lu *LocalizationUpdate) SetLanguage(l *Language) *LocalizationUpdate {
	return lu.SetLanguageID(l.ID)
}

// Mutation returns the LocalizationMutation object of the builder.
func (lu *LocalizationUpdate) Mutation() *LocalizationMutation {
	return lu.mutation
}

// ClearLanguage clears the "language" edge to the Language entity.
func (lu *LocalizationUpdate) ClearLanguage() *LocalizationUpdate {
	lu.mutation.ClearLanguage()
	return lu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LocalizationUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lu.hooks) == 0 {
		if err = lu.check(); err != nil {
			return 0, err
		}
		affected, err = lu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LocalizationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = lu.check(); err != nil {
				return 0, err
			}
			lu.mutation = mutation
			affected, err = lu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lu.hooks) - 1; i >= 0; i-- {
			if lu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LocalizationUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LocalizationUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LocalizationUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LocalizationUpdate) check() error {
	if _, ok := lu.mutation.LanguageID(); lu.mutation.LanguageCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Localization.language"`)
	}
	return nil
}

func (lu *LocalizationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   localization.Table,
			Columns: localization.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: localization.FieldID,
			},
		},
	}
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.LocalizationValue(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: localization.FieldLocalizationValue,
		})
	}
	if lu.mutation.LanguageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   localization.LanguageTable,
			Columns: []string{localization.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: language.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.LanguageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   localization.LanguageTable,
			Columns: []string{localization.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: language.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{localization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// LocalizationUpdateOne is the builder for updating a single Localization entity.
type LocalizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LocalizationMutation
}

// SetLanguageID sets the "language_id" field.
func (luo *LocalizationUpdateOne) SetLanguageID(i int) *LocalizationUpdateOne {
	luo.mutation.SetLanguageID(i)
	return luo
}

// SetLocalizationValue sets the "localizationValue" field.
func (luo *LocalizationUpdateOne) SetLocalizationValue(s string) *LocalizationUpdateOne {
	luo.mutation.SetLocalizationValue(s)
	return luo
}

// SetLanguage sets the "language" edge to the Language entity.
func (luo *LocalizationUpdateOne) SetLanguage(l *Language) *LocalizationUpdateOne {
	return luo.SetLanguageID(l.ID)
}

// Mutation returns the LocalizationMutation object of the builder.
func (luo *LocalizationUpdateOne) Mutation() *LocalizationMutation {
	return luo.mutation
}

// ClearLanguage clears the "language" edge to the Language entity.
func (luo *LocalizationUpdateOne) ClearLanguage() *LocalizationUpdateOne {
	luo.mutation.ClearLanguage()
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LocalizationUpdateOne) Select(field string, fields ...string) *LocalizationUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Localization entity.
func (luo *LocalizationUpdateOne) Save(ctx context.Context) (*Localization, error) {
	var (
		err  error
		node *Localization
	)
	if len(luo.hooks) == 0 {
		if err = luo.check(); err != nil {
			return nil, err
		}
		node, err = luo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LocalizationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = luo.check(); err != nil {
				return nil, err
			}
			luo.mutation = mutation
			node, err = luo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(luo.hooks) - 1; i >= 0; i-- {
			if luo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = luo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, luo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LocalizationUpdateOne) SaveX(ctx context.Context) *Localization {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LocalizationUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LocalizationUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LocalizationUpdateOne) check() error {
	if _, ok := luo.mutation.LanguageID(); luo.mutation.LanguageCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Localization.language"`)
	}
	return nil
}

func (luo *LocalizationUpdateOne) sqlSave(ctx context.Context) (_node *Localization, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   localization.Table,
			Columns: localization.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: localization.FieldID,
			},
		},
	}
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Localization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, localization.FieldID)
		for _, f := range fields {
			if !localization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != localization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.LocalizationValue(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: localization.FieldLocalizationValue,
		})
	}
	if luo.mutation.LanguageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   localization.LanguageTable,
			Columns: []string{localization.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: language.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.LanguageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   localization.LanguageTable,
			Columns: []string{localization.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: language.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Localization{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{localization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
