// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/MrGeorge2/hejdusekj/ent/language"
	"github.com/MrGeorge2/hejdusekj/ent/localization"
)

// LocalizationCreate is the builder for creating a Localization entity.
type LocalizationCreate struct {
	config
	mutation *LocalizationMutation
	hooks    []Hook
}

// SetLanguageID sets the "language_id" field.
func (lc *LocalizationCreate) SetLanguageID(i int) *LocalizationCreate {
	lc.mutation.SetLanguageID(i)
	return lc
}

// SetLocalizationValue sets the "localizationValue" field.
func (lc *LocalizationCreate) SetLocalizationValue(s string) *LocalizationCreate {
	lc.mutation.SetLocalizationValue(s)
	return lc
}

// SetLanguage sets the "language" edge to the Language entity.
func (lc *LocalizationCreate) SetLanguage(l *Language) *LocalizationCreate {
	return lc.SetLanguageID(l.ID)
}

// Mutation returns the LocalizationMutation object of the builder.
func (lc *LocalizationCreate) Mutation() *LocalizationMutation {
	return lc.mutation
}

// Save creates the Localization in the database.
func (lc *LocalizationCreate) Save(ctx context.Context) (*Localization, error) {
	var (
		err  error
		node *Localization
	)
	if len(lc.hooks) == 0 {
		if err = lc.check(); err != nil {
			return nil, err
		}
		node, err = lc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LocalizationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = lc.check(); err != nil {
				return nil, err
			}
			lc.mutation = mutation
			if node, err = lc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(lc.hooks) - 1; i >= 0; i-- {
			if lc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LocalizationCreate) SaveX(ctx context.Context) *Localization {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LocalizationCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LocalizationCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LocalizationCreate) check() error {
	if _, ok := lc.mutation.LanguageID(); !ok {
		return &ValidationError{Name: "language_id", err: errors.New(`ent: missing required field "Localization.language_id"`)}
	}
	if _, ok := lc.mutation.LocalizationValue(); !ok {
		return &ValidationError{Name: "localizationValue", err: errors.New(`ent: missing required field "Localization.localizationValue"`)}
	}
	if _, ok := lc.mutation.LanguageID(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required edge "Localization.language"`)}
	}
	return nil
}

func (lc *LocalizationCreate) sqlSave(ctx context.Context) (*Localization, error) {
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (lc *LocalizationCreate) createSpec() (*Localization, *sqlgraph.CreateSpec) {
	var (
		_node = &Localization{config: lc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: localization.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: localization.FieldID,
			},
		}
	)
	if value, ok := lc.mutation.LocalizationValue(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: localization.FieldLocalizationValue,
		})
		_node.LocalizationValue = value
	}
	if nodes := lc.mutation.LanguageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   localization.LanguageTable,
			Columns: []string{localization.LanguageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: language.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LanguageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LocalizationCreateBulk is the builder for creating many Localization entities in bulk.
type LocalizationCreateBulk struct {
	config
	builders []*LocalizationCreate
}

// Save creates the Localization entities in the database.
func (lcb *LocalizationCreateBulk) Save(ctx context.Context) ([]*Localization, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Localization, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LocalizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LocalizationCreateBulk) SaveX(ctx context.Context) []*Localization {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LocalizationCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LocalizationCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
