version: '3.4'

services:
  client:
    image: client
    restart: always
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
  
  server:
    image: server
    restart: always
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - MARIADB_HOST=database
      - MARIADB_PORT=3306
      - MARIADB_USER=root
      - MARIADB_PASSWORD=supersecret
      - MARIADB_DATABASE=GraphServer

  database:
    image: mariadb
    restart: always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=supersecret
    volumes:
      - database_volume:/var/lib/mysql

  proxy:
    image: nginx:stable-alpine
    ports:
      - 80:80
    restart: always
    volumes:
      - ./volumes/proxy:/etc/nginx/conf.d:ro
    depends_on:
      - client
      - server
volumes:
  database_volume: