// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Language is the predicate function for language builders.
type Language func(*sql.Selector)

// Localization is the predicate function for localization builders.
type Localization func(*sql.Selector)
