// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LanguagesColumns holds the columns for the "languages" table.
	LanguagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "language_code", Type: field.TypeString, Unique: true},
	}
	// LanguagesTable holds the schema information for the "languages" table.
	LanguagesTable = &schema.Table{
		Name:       "languages",
		Columns:    LanguagesColumns,
		PrimaryKey: []*schema.Column{LanguagesColumns[0]},
	}
	// LocalizationsColumns holds the columns for the "localizations" table.
	LocalizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "localization_value", Type: field.TypeString},
		{Name: "language_id", Type: field.TypeInt},
	}
	// LocalizationsTable holds the schema information for the "localizations" table.
	LocalizationsTable = &schema.Table{
		Name:       "localizations",
		Columns:    LocalizationsColumns,
		PrimaryKey: []*schema.Column{LocalizationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "localizations_languages_localizations",
				Columns:    []*schema.Column{LocalizationsColumns[2]},
				RefColumns: []*schema.Column{LanguagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "localization_language_id",
				Unique:  false,
				Columns: []*schema.Column{LocalizationsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LanguagesTable,
		LocalizationsTable,
	}
)

func init() {
	LocalizationsTable.ForeignKeys[0].RefTable = LanguagesTable
}
