// Code generated by entc, DO NOT EDIT.

package localization

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MrGeorge2/hejdusekj/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// LanguageID applies equality check predicate on the "language_id" field. It's identical to LanguageIDEQ.
func LanguageID(v int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLanguageID), v))
	})
}

// LocalizationValue applies equality check predicate on the "localizationValue" field. It's identical to LocalizationValueEQ.
func LocalizationValue(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLocalizationValue), v))
	})
}

// LanguageIDEQ applies the EQ predicate on the "language_id" field.
func LanguageIDEQ(v int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLanguageID), v))
	})
}

// LanguageIDNEQ applies the NEQ predicate on the "language_id" field.
func LanguageIDNEQ(v int) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLanguageID), v))
	})
}

// LanguageIDIn applies the In predicate on the "language_id" field.
func LanguageIDIn(vs ...int) predicate.Localization {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Localization(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLanguageID), v...))
	})
}

// LanguageIDNotIn applies the NotIn predicate on the "language_id" field.
func LanguageIDNotIn(vs ...int) predicate.Localization {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Localization(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLanguageID), v...))
	})
}

// LocalizationValueEQ applies the EQ predicate on the "localizationValue" field.
func LocalizationValueEQ(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueNEQ applies the NEQ predicate on the "localizationValue" field.
func LocalizationValueNEQ(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueIn applies the In predicate on the "localizationValue" field.
func LocalizationValueIn(vs ...string) predicate.Localization {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Localization(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLocalizationValue), v...))
	})
}

// LocalizationValueNotIn applies the NotIn predicate on the "localizationValue" field.
func LocalizationValueNotIn(vs ...string) predicate.Localization {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Localization(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLocalizationValue), v...))
	})
}

// LocalizationValueGT applies the GT predicate on the "localizationValue" field.
func LocalizationValueGT(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueGTE applies the GTE predicate on the "localizationValue" field.
func LocalizationValueGTE(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueLT applies the LT predicate on the "localizationValue" field.
func LocalizationValueLT(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueLTE applies the LTE predicate on the "localizationValue" field.
func LocalizationValueLTE(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueContains applies the Contains predicate on the "localizationValue" field.
func LocalizationValueContains(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueHasPrefix applies the HasPrefix predicate on the "localizationValue" field.
func LocalizationValueHasPrefix(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueHasSuffix applies the HasSuffix predicate on the "localizationValue" field.
func LocalizationValueHasSuffix(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueEqualFold applies the EqualFold predicate on the "localizationValue" field.
func LocalizationValueEqualFold(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldLocalizationValue), v))
	})
}

// LocalizationValueContainsFold applies the ContainsFold predicate on the "localizationValue" field.
func LocalizationValueContainsFold(v string) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldLocalizationValue), v))
	})
}

// HasLanguage applies the HasEdge predicate on the "language" edge.
func HasLanguage() predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LanguageTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LanguageTable, LanguageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLanguageWith applies the HasEdge predicate on the "language" edge with a given conditions (other predicates).
func HasLanguageWith(preds ...predicate.Language) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LanguageInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LanguageTable, LanguageColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Localization) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Localization) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Localization) predicate.Localization {
	return predicate.Localization(func(s *sql.Selector) {
		p(s.Not())
	})
}
