// Code generated by entc, DO NOT EDIT.

package language

const (
	// Label holds the string label denoting the language type in the database.
	Label = "language"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLanguageCode holds the string denoting the languagecode field in the database.
	FieldLanguageCode = "language_code"
	// EdgeLocalizations holds the string denoting the localizations edge name in mutations.
	EdgeLocalizations = "localizations"
	// Table holds the table name of the language in the database.
	Table = "languages"
	// LocalizationsTable is the table that holds the localizations relation/edge.
	LocalizationsTable = "localizations"
	// LocalizationsInverseTable is the table name for the Localization entity.
	// It exists in this package in order to avoid circular dependency with the "localization" package.
	LocalizationsInverseTable = "localizations"
	// LocalizationsColumn is the table column denoting the localizations relation/edge.
	LocalizationsColumn = "language_id"
)

// Columns holds all SQL columns for language fields.
var Columns = []string{
	FieldID,
	FieldLanguageCode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
