// Code generated by entc, DO NOT EDIT.

package language

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/MrGeorge2/hejdusekj/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// LanguageCode applies equality check predicate on the "languageCode" field. It's identical to LanguageCodeEQ.
func LanguageCode(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeEQ applies the EQ predicate on the "languageCode" field.
func LanguageCodeEQ(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeNEQ applies the NEQ predicate on the "languageCode" field.
func LanguageCodeNEQ(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeIn applies the In predicate on the "languageCode" field.
func LanguageCodeIn(vs ...string) predicate.Language {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Language(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLanguageCode), v...))
	})
}

// LanguageCodeNotIn applies the NotIn predicate on the "languageCode" field.
func LanguageCodeNotIn(vs ...string) predicate.Language {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Language(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLanguageCode), v...))
	})
}

// LanguageCodeGT applies the GT predicate on the "languageCode" field.
func LanguageCodeGT(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeGTE applies the GTE predicate on the "languageCode" field.
func LanguageCodeGTE(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeLT applies the LT predicate on the "languageCode" field.
func LanguageCodeLT(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeLTE applies the LTE predicate on the "languageCode" field.
func LanguageCodeLTE(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeContains applies the Contains predicate on the "languageCode" field.
func LanguageCodeContains(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeHasPrefix applies the HasPrefix predicate on the "languageCode" field.
func LanguageCodeHasPrefix(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeHasSuffix applies the HasSuffix predicate on the "languageCode" field.
func LanguageCodeHasSuffix(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeEqualFold applies the EqualFold predicate on the "languageCode" field.
func LanguageCodeEqualFold(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldLanguageCode), v))
	})
}

// LanguageCodeContainsFold applies the ContainsFold predicate on the "languageCode" field.
func LanguageCodeContainsFold(v string) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldLanguageCode), v))
	})
}

// HasLocalizations applies the HasEdge predicate on the "localizations" edge.
func HasLocalizations() predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LocalizationsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LocalizationsTable, LocalizationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLocalizationsWith applies the HasEdge predicate on the "localizations" edge with a given conditions (other predicates).
func HasLocalizationsWith(preds ...predicate.Localization) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(LocalizationsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LocalizationsTable, LocalizationsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Language) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Language) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Language) predicate.Language {
	return predicate.Language(func(s *sql.Selector) {
		p(s.Not())
	})
}
